# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "cp1" do |cp1|
    cp1.vm.box = "generic/debian12"
    cp1.vm.hostname = "controlplane1"
    cp1.vm.network "private_network", ip: "192.168.33.10"
    cp1.ssh.username = "vagrant"
    cp1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
    cp1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      mkdir -p /etc/k0s
    SHELL
    cp1.ssh.insert_key = false
      cp1.vm.provider "virtualbox" do |v|
      v.name = "controlplane1"
      v.memory = "4096"
      v.cpus = 1
    end
  end
  config.vm.define "w1" do |w1|
    w1.vm.box = "generic/debian12"
    w1.vm.hostname = "worker1"
    w1.vm.network "private_network", ip: "192.168.33.12"
    w1.ssh.username = "vagrant"
    w1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
    w1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
    w1.ssh.insert_key = false
    w1.vm.provider "virtualbox" do |v|
      v.name = "worker1"
      v.memory = "2048"
      v.cpus = 1
    end
  end
  config.vm.define "w2" do |w2|
    w2.vm.box = "generic/debian12"
    w2.vm.hostname = "worker2"
    w2.vm.network "private_network", ip: "192.168.33.13"
    w2.ssh.username = "vagrant"
    w2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
    w2.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
    w2.ssh.insert_key = false
    w2.vm.provider "virtualbox" do |v|
      v.name = "worker2"
      v.memory = "2048"
      v.cpus = 1
    end
  end
end